### PR TITLE
Update for .NET Core RC2

### PR DESCRIPTION
**Pull request by am11**
@oschwald, PTAL.
I will update GeoIP2 subsequently right after we get DB-Reader's `beta4` published.

### CODE REVIEW

**Comment by oschwald** [comment]
:+1: Thanks so much!

**Comment by am11** [comment]
@oschwald, the AppVeyor CI passed on my branch for 1701f6a: https://ci.appveyor.com/project/am11/maxmind-db-reader-dotnet/build/1.0.90.

I have added another commit which removes dotnet cli download for AppVeyor. Just saw that CLI Preview 1 (=> .NET Core RC2) is already available: http://www.appveyor.com/updates/2016/05/19. Seems like CI is ok with that decision: https://ci.appveyor.com/project/am11/maxmind-db-reader-dotnet/build/1.0.91. And it cut the build+test time from 1:13sec to 52sec! :)

Hopefully TavisCI will also bring the OOTB support sometime soon: https://github.com/travis-ci/travis-ci/issues/5189. 🎆

**Comment by oschwald** [comment]
So restoring, building, and testing now work well, but I am having an issue publishing on both Ubuntu and Windows:

```
Can not find runtime target for framework '.NETStandard,Version=v1.4' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
```

**Comment by am11** [comment]
Yup, that'd be number 2. We would either need to add `runtimes` section in `MaxMind.Db/project.json`. For instance:

```json
  "runtimes": {
    "centos.7-x64": {},
    "debian.8-x64": {},
    "fedora.23-x64": {},
    "linux-x64": {},
    "opensuse.13.2-x64": {},
    "osx.10.10-x64": {},
    "rhel.7-x64": {},
    "ubuntu.14.04-x64": {},
    "ubuntu.16.04-x64": {},
    "win7-x64": {},
    "win7-x86": {}
  }
```

See the latest available list of runtimes: https://github.com/dotnet/corefx/blob/50ed7398b8922bc987f89de9dd691234a5c6e4a2/pkg/Microsoft.NETCore.Platforms/runtime.json.

**Comment by oschwald** [comment]
Ah, ok. I packaged beta4 and pushed it to NuGet.

**Comment by am11** [comment]
Thanks! I will continue on semi-ready commit for geoip2 shortly. (AFK ATM)

**Comment by oschwald** [comment]
Thanks! 2.1.1-beta1 is available and has been indexed. It seems to fix the issue for me.

**Comment by am11** [comment]
@oschwald, [just wondering] have you find a way to publish without having a `runtimes` section? or was that change just didn't landed to GitHub?

**Comment by oschwald** [comment]
My release process has essentially been:

```
dotnet restore
dotnet build -c Release
dotnet pack -c Release
nuget push {nupkg from above}
```

I didn't work out the publishing bit. Looking more closely at the docs, I am not sure it is essential for a package being distributed through NuGet.

**Comment by am11** [comment]
Thanks. I think "runtimes" section requirement might be marked optional by dotnet CLI for `dotnet publish` command as well (since everything is MSIL and no native libs are used in our code).

**Pull request merged**
