### PR TITLE
Migrate build facade back to MSBuild

### PR DESCRIPTION
**Pull request by am11**
* `dotnet migrate`'d the solution with .NET CLI v1.0.0-RTM.
  * Uses to new project system; new CSPROJ schema, which is only
    compatible with donet-cli and VS2017 (runs on Windows & Unix)
    and xplat VS Code.
* Converted testing framework: nunit -> xunit.
  * Frankly speaking, xunit is a first class citizen and most up to
    the speed with varied frameworks.
  * Using `[Fact]` and `[Theory]` semantics.
  * Using `FluentAssertions` to diversify the way of writing assertions.
* Updated the CI scripts.

### CODE REVIEW

**Comment by am11** [comment]
@oschwald, AppVeyor build will fail until VS2017 RTM worker is ready. Currently they have VS2017 RC, which has a bug (can't make benchmark project executable without explicit RID: https://github.com/dotnet/sdk/issues/357#issuecomment-284697314)

If all the rest of (the invasive) changes get approved, we can probably hold off on merging this until AppVeyor shows all green (they said it will happen this week or the next). :)

**Comment by oschwald** [comment]
Thanks so much for your work on this! :100: I did a review of the changes, and they seem very reasonable to me. I'll do another pass and some build tests once AppVeyor is updated.

**Comment by am11** [comment]
@oschwald, thanks! AppVeyor has VS2017 RTM bits now. I have re-pushed with few more changes (added `.runsettings` file for VS2017 test runs: setting architecture to x86_64). All CI jobs are passing. 🏁

**Comment by oschwald** [comment]
Thanks again for all of your work on this! It looks great.

**Pull request merged**
